---
title: Data and Democracy Lab
timezone: UTC
collections:
  category_pages:
    title: Categories
    output: true
    permalink: "/:title"
    layout: category
  about:
    title: About Us
    output: true
    permalink: "/:title"
    layout: category
  jobs:
    title: Jobs
    output: false
  people:
    title: People
    output: false
  posts:
    title: Posts
    permalink: "/posts/:title"
    output: true
  uploads:
    title: Uploads
    output: true
  publications:
    title: Publications
    output: true
name: Data and Democracy Lab
url: https://www.mggg.org
author: Data and Democracy Lab
description:
  A nonpartisan research organization studying applications of data science to democratic systems.
logo: "/assets/draft_logo.svg"
google_site_verification: jaL3ii25-g2LejBrllWbH-DmyT7b-vJw8URj-tvq8kE
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass
include:
  - _redirects
defaults:
  values:
    hidden: false
